### ISSUE TITLE
Support for WebP?

### ISSUE THREAD

**Issue by MrWheyne** [UrbanCMC/PlayniteExtensions#1]
WebP is a fairly recent image compression format developed by Google and is rapidly gaining traction as a new stardard, as it is capable of image quality on par with PNG, with much smaller file sizes on par and beyond JPEG. It also supports alpha channel (transparency) and animations. Playnite has added support for it since a while back, but most metadata sources sadly still rely on old formats, and manually converting each media type for each game is cumbersome and a virtually endless task for folks with large libraries. This extension has the potential to change that paradigm and finally make an entire WebP media library a reality (including hopefully media from Extra Metadata, such as logos). It would improve image quality and load times for every type of media, with a fraction of the storage consumption.

[Sample Comparisons](https://developers.google.com/speed/webp/gallery)

**Comment by UrbanCMC** [comment]
Great suggestions! WebP should be pretty easy to add, and I'll have a separate look at adding support for images from other extensions.

**Comment by UrbanCMC** [comment]
WebP is now supported with v1.2 of the extension.

As for the Logos from ExtraMetadataLoader, I'm afraid that extension uses hardcoded names (`Logo.png`) so converting to a different format is not possible. Limiting the maximum size of a Logo is already possible through ExtraMetadataLoader's settings.
