### ISSUE TITLE
WebP conversion altering transparent images

### ISSUE THREAD

**Issue by MrWheyne** [UrbanCMC/PlayniteExtensions#4]
When a transparent image (icons, in this case) is converted through the extension, it gets warped and garbled. 100% reproduceable, as it happened to every tested file.

**Comment by UrbanCMC** [comment]
Can you give me examples of where you see this?

I noticed something like this in the "Media" page when editing a game's details. This icon, for example, actually has a transparent background, but Playnite is showing white here:
![image](https://github.com/UrbanCMC/PlayniteExtensions/assets/9725089/eb2833f2-83b1-4ebc-9599-6b66dd725865)

However, the icon looks completely fine in my game list:
![image](https://github.com/UrbanCMC/PlayniteExtensions/assets/9725089/2c2571ea-4198-4ec6-a23f-236ac1d58a22)

**Comment by MrWheyne** [comment]
Indeed, you're correct. My testing was limited to viewing those in the Edit window and File Explorer. I suppose this is a rendering issue from FE, which is probably how the Edit window fetches the files. Tested with QuickLook and Firefox and they also look OK in those. I'm closing this report.
