### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by MrWheyne** [UrbanCMC/PlayniteExtensions#5]
Right now the extension freezes the entire app when it is running. It might lead users to think the app froze by itself when in reality it's just allocating all resources to generate the new conversions and update the DB references. It would be interesting to have a progress bar pop-up to let users know for how much longer the script will run, especially for when converting entire media libraries for the first time. Alternatively, a simple pop-up with "Converting media, this might take a while..." would also work just fine, just as a way to make users aware.

**Comment by UrbanCMC** [comment]
v1.3 now shows a progress bar dialog while optimizing at least one game.
