### ISSUE TITLE
[MetadataImageOptimizer] Playnite crash during library update

### ISSUE THREAD

**Issue by nikolay-borzov** [UrbanCMC/PlayniteExtensions#8]
Happens during library update

> The process cannot access the file '...\optimize-queue' because it is being used by another process

[MetadataImageOptimizer_crash_logs.zip](https://github.com/user-attachments/files/16624076/MetadataImageOptimizer_crash_logs.zip)

**Comment by UrbanCMC** [comment]
Thanks for reporting the issue.
I've pushed v1.5 that should prevent this from happening again.
