### ISSUE TITLE
How do I specify the desired filesize/type?

### ISSUE THREAD

**Issue by sidarous** [UrbanCMC/PlayniteExtensions#9]
The extension is not found in the dropdown menu -> extensions. I can see it in the addon browser, but there is no UI that I can find. Also, the YAML file does not seem to have a clear way to specify this information.

Apologies if this is the wrong forum to answer these questions.

**Comment by UrbanCMC** [comment]
Extension settings are located in the Add-ons browser (F9), in the first section. The settings for this extension can be found in the Generic section.
![image](https://github.com/user-attachments/assets/60ba24f3-a57c-42fb-91ba-e4ce52bff5c4)

**Comment by sidarous** [comment]
Thanks so much, I completely misunderstood that interface.

**Comment by sidarous** [comment]
Thanks so much, I completely misunderstood that interface.
